### PR TITLE
YM-288 | Fix list view

### PR DESCRIPTION
**Pull request by Jokinen**
The new version of `react-admin` dropped support for the way we were using the library. Although the version change was minor, and should therefore have been backwards compatible, we used `react-admin` in a special way which `react-admin` didn't likely consider to be officially supported.

The fix here was to refactor the list view in a way where it's more in line with the `react-admin` ethos. This way we can retain the newer version that does not include library side bugs that caused errors in some of our views.

I have tested this view by hand, because the functionality here heavily depends on the API. `e2e` integration is in the pipeline as its own separate task. I've also tested (by hand) the other views with happy paths:
- Profile "show" page
- Profile edit page
- Profile create page

### CODE REVIEW

**Review by tuovinensanttu — COMMENTED** [review]
Not sure why, but it seems that translations for Tila, Kuvauslupa & Kieli are broken.

Screenshot 2020-09-10 at 14 16 04

**Comment by Jokinen** [comment]
Good catch. Maybe this is because they were previously translated in the data model instead of the view layer?

**Comment by tuovinensanttu** [comment]
List values are now shown correctly 👍. There seems to something fishy going on with the component though. After entering the List (search) view and then navigating back to Dashboard, for some reason search is executed and navigation is aborted due `setState` call while rendering.

**Review by tuovinensanttu — APPROVED** [review]
LGMT 👍

**Pull request merged**
